import type { MetricsEntry } from "./schema.js";

/** A trimmed Shepherd registry entry: one or two metrics per family, taken from the Shepherd measurement audit. */
export const SHEPHERD_ENTRY: MetricsEntry = {
  schema: "titan.metrics/v1",
  area: "shepherd",
  owner: "titan-coord",
  stores: [
    { id: "ledger", kind: "sqlite", readonly: true },
    { id: "health", kind: "http", readonly: true },
  ],
  metrics: [
    {
      id: "shepherd.availability.service_up",
      family: "availability",
      title: "Service up",
      definition: "Share of 60 s probes where /health answers ok with identity",
      unit: "ratio",
      source: {
        anchor: "products/factory/src/serve.ts#health",
        store: "health",
        captured: "P",
        gapSlice: "S1",
      },
      query: {
        kind: "http",
        store: "health",
        text: "/health",
        valuePath: "ok",
      },
      cadence: "1m",
      slo: {
        objective: "99.5% per 24 h",
        target: 0.995,
        op: ">=",
        window: "1d",
        alert: { threshold: 0.995, sustain: 3 },
      },
      surfaces: ["health", "dashboard"],
      answers: [1],
    },
    {
      id: "shepherd.availability.stuck_runs",
      family: "availability",
      title: "Stuck runs",
      definition: "Paused runs with no pending gate",
      unit: "count",
      source: {
        anchor: "products/factory/src/shepherd/store.ts#workflow_run",
        store: "ledger",
        captured: "Y",
      },
      query: {
        kind: "sql",
        store: "ledger",
        text: "select count(*) from workflow_run where status = 'paused'",
      },
      cadence: "1h",
      slo: {
        objective: "0 orphans",
        target: 0,
        op: "<=",
        window: "1d",
        alert: { threshold: 1, sustain: 1 },
      },
      surfaces: ["status", "digest"],
      answers: [2, 3],
    },
    {
      id: "shepherd.flow.merge_verdict_to_merged",
      family: "flow",
      title: "MERGE to merged",
      definition: "Minutes from a MERGE verdict to the merge step completing",
      unit: "minutes",
      source: {
        anchor: "products/factory/src/shepherd/stats.ts#mergeVerdictAt",
        store: "ledger",
        captured: "Y",
      },
      cadence: "1d",
      surfaces: ["stats", "digest"],
      answers: [4],
    },
    {
      id: "shepherd.quality.escaped_defects",
      family: "quality",
      title: "Escaped defects",
      definition: "Merges whose post-merge main CI is red",
      unit: "ratio",
      source: {
        anchor: "products/factory/src/shepherd/main-red.ts#mainRed",
        store: "ledger",
        captured: "Y",
      },
      cadence: "1w",
      surfaces: ["stats", "health"],
      answers: [5],
    },
    {
      id: "shepherd.owner-load.waiting_now",
      family: "owner-load",
      title: "Waiting on the owner now",
      definition: "Pending gates by kind with age",
      unit: "count",
      source: {
        anchor: "products/factory/src/shepherd/store.ts#hitl_gate",
        store: "ledger",
        captured: "Y",
      },
      cadence: "1h",
      surfaces: ["dashboard", "status", "digest"],
      answers: [6],
    },
    {
      id: "shepherd.cost.reviewer_usd_per_merge",
      family: "cost",
      title: "Reviewer dollars per merged PR",
      definition:
        "List-price cost of reviewer sessions on a run divided by its merges",
      unit: "usd",
      source: {
        anchor: "products/factory/src/shepherd/stats.ts#reviewCost",
        store: "ledger",
        captured: "N",
        gapSlice: "S7",
      },
      cadence: "1d",
      surfaces: ["stats", "digest"],
      answers: [7],
    },
    {
      id: "shepherd.business.merges_per_day",
      family: "business",
      title: "Merges per day",
      definition: "Shepherd merges per day per repo",
      unit: "count",
      source: {
        anchor: "products/factory/src/shepherd/stats.ts#mergesPerDay",
        store: "ledger",
        captured: "Y",
      },
      cadence: "1d",
      surfaces: ["stats", "digest"],
      answers: [8],
    },
  ],
  reports: [
    {
      id: "weekly-flow",
      title: "Weekly flow",
      metrics: ["shepherd.flow.merge_verdict_to_merged"],
    },
  ],
  lastAudit: {
    at: "2026-10-08T00:00:00.000Z",
    codeRev: "0000000",
    report: "shepherd-measurement-audit-2026-10-08.json",
  },
};
