/**
 * Synthetic inputs with the verdicts agent-chat's own `checkDecision` and `unlockTableRow`
 * (`src/broker/decisions.ts` on main) returned for them. Regenerate from agent-chat, never by hand.
 */
export interface UnlockParityCase {
  question: string;
  answer: string;
  category: string;
  row: string | null;
  decision: "ok" | "not_decidable" | "unlock_table";
}

export const UNLOCK_PARITY: readonly UnlockParityCase[] = [
  {
    question: "Merge PR 12 now?",
    answer: "yes",
    category: "tech_design",
    row: "merge",
    decision: "unlock_table",
  },
  {
    question: "Should we squash the branch?",
    answer: "no",
    category: "tech_design",
    row: "merge",
    decision: "unlock_table",
  },
  {
    question: "Which emerging pattern fits?",
    answer: "the first",
    category: "tech_design",
    row: null,
    decision: "ok",
  },
  {
    question: "Cut the release today?",
    answer: "yes",
    category: "scope_priority",
    row: "publish or release",
    decision: "unlock_table",
  },
  {
    question: "Release the claim on the task?",
    answer: "yes",
    category: "agent_ops",
    row: "publish or release",
    decision: "unlock_table",
  },
  {
    question: "Run npm pack first?",
    answer: "ok",
    category: "tech_design",
    row: "publish or release",
    decision: "unlock_table",
  },
  {
    question: "Add a changeset?",
    answer: "yes",
    category: "tech_design",
    row: "publish or release",
    decision: "unlock_table",
  },
  {
    question: "Deploy the worker?",
    answer: "go",
    category: "agent_ops",
    row: "deploy",
    decision: "unlock_table",
  },
  {
    question: "Reload the launchd job?",
    answer: "yes",
    category: "agent_ops",
    row: "deploy",
    decision: "unlock_table",
  },
  {
    question: "Buy the larger plan?",
    answer: "yes",
    category: "scope_priority",
    row: "money",
    decision: "unlock_table",
  },
  {
    question: "Spend $40 on credits?",
    answer: "ok",
    category: "scope_priority",
    row: "money",
    decision: "unlock_table",
  },
  {
    question: "Place an order for parts?",
    answer: "yes",
    category: "scope_priority",
    row: "money",
    decision: "unlock_table",
  },
  {
    question: "Use the second account?",
    answer: "yes",
    category: "agent_ops",
    row: "external account",
    decision: "unlock_table",
  },
  {
    question: "Log in with the passkey?",
    answer: "ok",
    category: "agent_ops",
    row: "external account",
    decision: "unlock_table",
  },
  {
    question: "Delete the stale branch?",
    answer: "yes",
    category: "agent_ops",
    row: "deletion",
    decision: "unlock_table",
  },
  {
    question: "Run git reset --hard?",
    answer: "yes",
    category: "tech_design",
    row: "deletion",
    decision: "unlock_table",
  },
  {
    question: "Wipe the cache directory?",
    answer: "fine",
    category: "agent_ops",
    row: "deletion",
    decision: "unlock_table",
  },
  {
    question: "Restart the broker?",
    answer: "yes",
    category: "agent_ops",
    row: "broker restart or cap lift",
    decision: "unlock_table",
  },
  {
    question: "Make the repo public?",
    answer: "yes",
    category: "scope_priority",
    row: "publicity or sharing",
    decision: "unlock_table",
  },
  {
    question: "Share this with the team?",
    answer: "sure",
    category: "scope_priority",
    row: "publicity or sharing",
    decision: "unlock_table",
  },
  {
    question: "Email it to the vendor?",
    answer: "yes",
    category: "scope_priority",
    row: "third-party send",
    decision: "unlock_table",
  },
  {
    question: "Edit CLAUDE.md for the rule?",
    answer: "yes",
    category: "tech_design",
    row: "settings or policy edit",
    decision: "unlock_table",
  },
  {
    question: "Update the profile permissions?",
    answer: "yes",
    category: "agent_ops",
    row: "settings or policy edit",
    decision: "unlock_table",
  },
  {
    question: "Approve the plan?",
    answer: "yes",
    category: "scope_priority",
    row: "permission prompt",
    decision: "unlock_table",
  },
  {
    question: "Which schema version should we use?",
    answer: "v2",
    category: "tech_design",
    row: null,
    decision: "ok",
  },
  {
    question: "Keep going with the next task?",
    answer: "yes",
    category: "session_control",
    row: null,
    decision: "ok",
  },
  {
    question: "Which task first?",
    answer: "the parser",
    category: "scope_priority",
    row: null,
    decision: "ok",
  },
  {
    question: "Spawn two more implementers?",
    answer: "yes",
    category: "agent_ops",
    row: null,
    decision: "ok",
  },
  {
    question: "Which schema version should we use?",
    answer: "merge it",
    category: "tech_design",
    row: "merge",
    decision: "unlock_table",
  },
  {
    question: "Which color for the chart?",
    answer: "blue",
    category: "visual_taste",
    row: null,
    decision: "not_decidable",
  },
  {
    question: "Which phone is yours?",
    answer: "the old one",
    category: "info_request",
    row: null,
    decision: "not_decidable",
  },
  {
    question: "Merge the PR?",
    answer: "yes",
    category: "merge_gate",
    row: "merge",
    decision: "not_decidable",
  },
  {
    question: "Cut 0.2?",
    answer: "yes",
    category: "release_publish",
    row: null,
    decision: "not_decidable",
  },
  {
    question: "Anything else?",
    answer: "no",
    category: "other",
    row: null,
    decision: "not_decidable",
  },
  {
    question: "Proceed with the fallback design?",
    answer: "yes",
    category: "tech_design",
    row: null,
    decision: "ok",
  },
];
