import * as path from "node:path";
import { workingTreeSource, type IndexSource } from "./index-source.js";

/**
 * Generated-code detection. Generated files (codegen output, e.g. an OpenAPI
 * `client.gen.ts`) churn and re-export in bulk, so they dominate hotspots and
 * unused-exports with noise that no human maintains. This module supplies one
 * reusable predicate — {@link isGeneratedFile} — used to mark such files so the
 * hotspot / unused-export surfaces can exclude them at their shared boundary.
 *
 * Detection has two tiers: the authoritative `.gitattributes linguist-generated`
 * markers a repo already declares, and a filename/path heuristic fallback for
 * repos that declare nothing.
 */

// Fallback heuristic: `*.gen.*` / `*.generated.*` basenames and any path with a
// `generated/` segment. Anchored to a segment boundary so `regenerated/` and a
// stray `foogen.ts` don't match.
const HEURISTIC_FILE_RE = /(?:^|\/)[^/]*\.(?:gen|generated)\.[^/]*$/;
const HEURISTIC_DIR_RE = /(?:^|\/)generated\//;

/** True when a path looks generated by filename/dir convention alone. */
export function isGeneratedByHeuristic(id: string): boolean {
  return HEURISTIC_FILE_RE.test(id) || HEURISTIC_DIR_RE.test(id);
}

/**
 * A file is generated when it matches a repo-declared `linguist-generated`
 * pattern or the filename/path heuristic. `patterns` come from
 * {@link parseGeneratedPatterns}; pass `[]` when no `.gitattributes` exists.
 */
export function isGeneratedFile(
  id: string,
  patterns: readonly RegExp[],
): boolean {
  for (const rx of patterns) if (rx.test(id)) return true;
  return isGeneratedByHeuristic(id);
}

/** Read `<rootDir>/.gitattributes` and compile its linguist-generated patterns. */
export function loadGeneratedPatterns(
  rootDir: string,
  source: IndexSource = workingTreeSource(),
): RegExp[] {
  try {
    const content = source.readFile(path.join(rootDir, ".gitattributes"));
    return parseGeneratedPatterns(content);
  } catch {
    return [];
  }
}

interface GeneratedRule {
  readonly rx: RegExp;
  readonly generated: boolean;
}

/**
 * Parse `.gitattributes` text into regexes for every path pattern marked
 * `linguist-generated` (bare, or `=true`). Git applies the last matching line,
 * so a later `-linguist-generated` / `=false` / `!linguist-generated` line opts
 * a path back out: each returned regex excludes the opt-out patterns that
 * follow its line. Within one line the last attribute token wins.
 */
export function parseGeneratedPatterns(content: string): RegExp[] {
  const rules = parseGeneratedRules(content);
  const out: RegExp[] = [];
  rules.forEach((rule, i) => {
    if (!rule.generated) return;
    const optOuts = rules.slice(i + 1).filter((r) => !r.generated);
    out.push(excluding(rule.rx, optOuts.map((r) => r.rx)));
  });
  return out;
}

function parseGeneratedRules(content: string): GeneratedRule[] {
  const rules: GeneratedRule[] = [];
  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const parsed = /^("(?:[^"\\]|\\.)*"|\S+)\s*(.*)$/.exec(line);
    if (!parsed) continue;
    const generated = generatedAttr(parsed[2]!.split(/\s+/).filter(Boolean));
    if (generated === undefined) continue;
    rules.push({ rx: gitattributesPatternToRegex(unquote(parsed[1]!)), generated });
  }
  return rules;
}

// Every pattern regex is anchored at both ends, so a lookahead over the
// opt-out sources rejects exactly the ids a later line unsets.
function excluding(rx: RegExp, optOuts: readonly RegExp[]): RegExp {
  if (optOuts.length === 0) return rx;
  const rejected = optOuts.map((o) => `(?:${o.source})`).join("|");
  return new RegExp(`(?!${rejected})(?:${rx.source})`);
}

/** Resolve the effective linguist-generated value from a line's attribute tokens. */
function generatedAttr(attrs: readonly string[]): boolean | undefined {
  let value: boolean | undefined;
  for (const a of attrs) {
    if (a === "linguist-generated" || a === "linguist-generated=true") value = true;
    else if (OPT_OUT_TOKENS.has(a)) value = false;
  }
  return value;
}

const OPT_OUT_TOKENS = new Set([
  "-linguist-generated",
  "linguist-generated=false",
  "!linguist-generated",
]);

function unquote(token: string): string {
  return token.startsWith('"') && token.endsWith('"')
    ? token.slice(1, -1).replace(/\\(.)/g, "$1")
    : token;
}

/**
 * Convert a gitignore-style `.gitattributes` path pattern to a regex matched
 * against a repo-relative posix id: a slash-free pattern matches at any depth
 * (`*.gen.ts`), a leading or inner slash anchors to the root, a non-final `**`
 * segment matches zero or more directories, a final `**` segment matches
 * everything inside, `*`/`?` stay within a segment, and a trailing `/` matches
 * a directory prefix. The result is anchored at both ends.
 */
export function gitattributesPatternToRegex(pattern: string): RegExp {
  let p = pattern;
  const isDir = p.endsWith("/");
  if (isDir) p = p.slice(0, -1);
  const anchored = p.includes("/");
  if (p.startsWith("/")) p = p.slice(1);
  const prefix = anchored ? "^" : "^(?:.*/)?";
  return new RegExp(prefix + globBody(p) + (isDir ? "(?:/.*)?$" : "$"));
}

function globBody(p: string): string {
  const segments = p.split("/");
  return segments
    .map((seg, i) => {
      const last = i === segments.length - 1;
      if (seg === "**") return last ? ".+" : "(?:.*/)?";
      return globSegment(seg) + (last ? "" : "/");
    })
    .join("");
}

function globSegment(seg: string): string {
  let out = "";
  for (const c of seg) {
    if (c === "*") out += "[^/]*";
    else if (c === "?") out += "[^/]";
    else out += c.replace(/[.+(){}|^$\\[\]]/, "\\$&");
  }
  return out;
}
