import { readFileSync } from "node:fs";
import * as path from "node:path";

/**
 * Generated-code detection. Generated files (codegen output, e.g. an OpenAPI
 * `client.gen.ts`) churn and re-export in bulk, so they dominate hotspots and
 * unused-exports with noise that no human maintains. This module supplies one
 * reusable predicate — {@link isGeneratedFile} — used to mark such files so the
 * hotspot / unused-export surfaces can exclude them at their shared boundary.
 *
 * Detection has two tiers: the authoritative `.gitattributes linguist-generated`
 * markers a repo already declares, and a filename/path heuristic fallback for
 * repos that declare nothing.
 */

// Fallback heuristic: `*.gen.*` / `*.generated.*` basenames and any path with a
// `generated/` segment. Anchored to a segment boundary so `regenerated/` and a
// stray `foogen.ts` don't match.
const HEURISTIC_FILE_RE = /(?:^|\/)[^/]*\.(?:gen|generated)\.[^/]*$/;
const HEURISTIC_DIR_RE = /(?:^|\/)generated\//;

/** True when a path looks generated by filename/dir convention alone. */
export function isGeneratedByHeuristic(id: string): boolean {
  return HEURISTIC_FILE_RE.test(id) || HEURISTIC_DIR_RE.test(id);
}

/**
 * A file is generated when it matches a repo-declared `linguist-generated`
 * pattern or the filename/path heuristic. `patterns` come from
 * {@link parseGeneratedPatterns}; pass `[]` when no `.gitattributes` exists.
 */
export function isGeneratedFile(
  id: string,
  patterns: readonly RegExp[],
): boolean {
  for (const rx of patterns) if (rx.test(id)) return true;
  return isGeneratedByHeuristic(id);
}

/** Read `<rootDir>/.gitattributes` and compile its linguist-generated patterns. */
export function loadGeneratedPatterns(rootDir: string): RegExp[] {
  try {
    const content = readFileSync(path.join(rootDir, ".gitattributes"), "utf-8");
    return parseGeneratedPatterns(content);
  } catch {
    return [];
  }
}

/**
 * Parse `.gitattributes` text into regexes for every path pattern marked
 * `linguist-generated` (bare, or `=true`). A later `-linguist-generated` /
 * `=false` on the same line wins (git's last-attribute-wins rule), letting a
 * repo opt a path back out.
 */
export function parseGeneratedPatterns(content: string): RegExp[] {
  const out: RegExp[] = [];
  for (const raw of content.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const parsed = /^("(?:[^"\\]|\\.)*"|\S+)\s*(.*)$/.exec(line);
    if (!parsed) continue;
    const pattern = unquote(parsed[1]!);
    if (generatedAttr(parsed[2]!.split(/\s+/).filter(Boolean)) === true) {
      out.push(gitattributesPatternToRegex(pattern));
    }
  }
  return out;
}

/** Resolve the effective linguist-generated value from a line's attribute tokens. */
function generatedAttr(attrs: readonly string[]): boolean | undefined {
  let value: boolean | undefined;
  for (const a of attrs) {
    if (a === "linguist-generated" || a === "linguist-generated=true") value = true;
    else if (a === "-linguist-generated" || a === "linguist-generated=false") value = false;
  }
  return value;
}

function unquote(token: string): string {
  return token.startsWith('"') && token.endsWith('"')
    ? token.slice(1, -1).replace(/\\(.)/g, "$1")
    : token;
}

/**
 * Convert a gitignore-style `.gitattributes` path pattern to a regex matched
 * against a repo-relative posix id: a slash-free pattern matches at any depth
 * (`*.gen.ts`), a pattern with a slash anchors to the root, `**` crosses dirs,
 * `*`/`?` stay within a segment, and a trailing `/` matches a directory prefix.
 */
export function gitattributesPatternToRegex(pattern: string): RegExp {
  let p = pattern;
  const isDir = p.endsWith("/");
  if (isDir) p = p.slice(0, -1);
  let body = "";
  for (let i = 0; i < p.length; i++) {
    const c = p[i]!;
    if (c === "*" && p[i + 1] === "*") {
      body += ".*";
      i++;
    } else if (c === "*") body += "[^/]*";
    else if (c === "?") body += "[^/]";
    else body += c.replace(/[.+(){}|^$\\[\]]/, "\\$&");
  }
  const prefix = p.includes("/") ? "^" : "(?:^|/)";
  return new RegExp(prefix + body + (isDir ? "(?:/|$)" : "$"));
}
