import type { Profile } from "../schema/profile.js";
import type { StyleRule } from "../schema/style-rule.js";
import type { GeneratedFile } from "./types.js";

function getConvention<T>(
  section: Record<string, StyleRule>,
  key: string,
): T | undefined {
  const rule = section[key];
  if (!rule) return undefined;
  return rule.convention as T;
}

export function generateEditorConfigExport(
  profile: Profile,
): GeneratedFile {
  const formatting = profile.formatting;
  const lines: string[] = [];

  lines.push("# Generated by codewatch");
  lines.push("root = true");
  lines.push("");
  lines.push("[*]");

  const indentStyle = getConvention<string>(formatting, "indentStyle");
  if (indentStyle) {
    const value =
      indentStyle === "spaces"
        ? "space"
        : indentStyle === "tabs"
          ? "tab"
          : indentStyle;
    lines.push(`indent_style = ${value}`);
  }

  const indentSize = getConvention<number>(formatting, "indentSize");
  if (indentSize !== undefined) {
    lines.push(`indent_size = ${indentSize}`);
  }

  const trailingNewline = getConvention<boolean>(
    formatting,
    "trailingNewline",
  );
  if (trailingNewline !== undefined) {
    lines.push(`insert_final_newline = ${trailingNewline}`);
  }

  lines.push("end_of_line = lf");
  lines.push("charset = utf-8");
  lines.push("trim_trailing_whitespace = true");

  const lineLength = getConvention<number>(formatting, "lineLength");
  if (lineLength !== undefined) {
    lines.push(`max_line_length = ${lineLength}`);
  }

  lines.push("");

  return {
    path: ".editorconfig",
    content: lines.join("\n"),
  };
}
