import { PROFILE_CATEGORIES, type Profile } from "../schema/profile.js";
import type { GeneratedFile } from "./types.js";
import {
  toEslintSeverity,
  buildImportOrderRule,
} from "./eslint-rules.js";

interface EslintRuleEntry {
  plugin: string;
  rule: string;
  severity: "error" | "warn" | "off";
  options?: unknown[];
}

function collectEslintExtensions(profile: Profile): EslintRuleEntry[] {
  const entries: EslintRuleEntry[] = [];
  const thresholds = profile.severityThresholds;

  for (const category of PROFILE_CATEGORIES) {
    const section = profile[category];
    if (!section) continue;

    for (const [, rule] of Object.entries(section)) {
      if (!rule.extensions?.eslint) continue;

      const ext = rule.extensions.eslint as {
        rule: string;
        options?: unknown[];
      };

      const sev = toEslintSeverity(rule.confidence, thresholds);
      if (sev === null) continue;

      const plugin = ext.rule.includes("/")
        ? ext.rule.split("/").slice(0, -1).join("/")
        : "";

      entries.push({
        plugin,
        rule: ext.rule,
        severity: sev === "info" ? "warn" : sev,
        options: ext.options,
      });
    }
  }

  return entries;
}

function addImportOrderRule(profile: Profile, entries: EslintRuleEntry[]): void {
  const result = buildImportOrderRule(profile);
  if (!result) return;

  const [ruleName, ruleConfig] = result;
  const configArray = ruleConfig as unknown[];
  const severity = configArray[0] as string;
  if (severity === "info") return;

  entries.push({
    plugin: "perfectionist",
    rule: ruleName,
    severity: severity as "error" | "warn",
    options: [configArray[1]],
  });
}

function detectRequiredPlugins(entries: EslintRuleEntry[]): Set<string> {
  const plugins = new Set<string>();
  for (const entry of entries) {
    if (entry.plugin.includes("@typescript-eslint")) {
      plugins.add("@typescript-eslint");
    }
    if (entry.plugin === "perfectionist") {
      plugins.add("perfectionist");
    }
    if (entry.plugin.includes("unicorn")) {
      plugins.add("unicorn");
    }
    if (entry.plugin.includes("jsdoc")) {
      plugins.add("jsdoc");
    }
  }
  return plugins;
}

function generateImportStatements(plugins: Set<string>): string[] {
  const imports: string[] = [];
  if (plugins.has("@typescript-eslint")) {
    imports.push(`import tseslint from "@typescript-eslint/eslint-plugin";`);
    imports.push(`import tsparser from "@typescript-eslint/parser";`);
  }
  if (plugins.has("perfectionist")) {
    imports.push(`import perfectionist from "eslint-plugin-perfectionist";`);
  }
  if (plugins.has("unicorn")) {
    imports.push(`import unicorn from "eslint-plugin-unicorn";`);
  }
  if (plugins.has("jsdoc")) {
    imports.push(`import jsdoc from "eslint-plugin-jsdoc";`);
  }
  return imports;
}

function buildRulesObject(
  entries: EslintRuleEntry[],
): Record<string, unknown> {
  const rules: Record<string, unknown> = {};
  for (const entry of entries) {
    if (entry.options && entry.options.length > 0) {
      rules[entry.rule] = [entry.severity, ...entry.options];
    } else {
      rules[entry.rule] = entry.severity;
    }
  }
  return rules;
}

export function generateEslintExport(profile: Profile): GeneratedFile {
  const entries = collectEslintExtensions(profile);
  addImportOrderRule(profile, entries);

  const plugins = detectRequiredPlugins(entries);
  const imports = generateImportStatements(plugins);
  const rules = buildRulesObject(entries);

  const header = [
    `// Generated by codewatch for ${profile.author}`,
    `// Date: ${profile.generated}`,
    `// Do not edit manually - regenerate with: codewatch export --format eslint`,
    "",
  ].join("\n");

  const content = [
    header,
    ...imports,
    "",
    `export default ${JSON.stringify({ rules }, null, 2)};`,
    "",
  ].join("\n");

  return { path: "eslint.config.js", content };
}
