import { describe, it, expect } from "vitest";
import { generateEslintExport } from "./eslint.js";
import type { Profile } from "../schema/profile.js";

function makeProfile(overrides: Partial<Profile> = {}): Profile {
  return {
    schemaVersion: "1.0.0",
    author: "testuser",
    generated: "2026-02-27",
    sources: [],
    naming: {},
    structure: {},
    documentation: {},
    errorHandling: {},
    formatting: {},
    patterns: {},
    idioms: { detected: [] },
    antiPatterns: { acknowledged: [] },
    overrides: [],
    severityThresholds: { error: 0.85, warn: 0.60, info: 0.40 },
    ...overrides,
  };
}

describe("generateEslintExport", () => {
  it("returns a single file with eslint.config.js path", () => {
    const file = generateEslintExport(makeProfile());
    expect(file.path).toBe("eslint.config.js");
  });

  it("generates valid JavaScript content with export default", () => {
    const file = generateEslintExport(makeProfile());
    expect(file.content).toContain("export default");
  });

  it("includes a header comment with generation metadata", () => {
    const file = generateEslintExport(makeProfile());
    expect(file.content).toContain("Generated by codewatch");
    expect(file.content).toContain("testuser");
  });

  it("includes @typescript-eslint import when naming rules have eslint extensions", () => {
    const profile = makeProfile({
      naming: {
        variables: {
          convention: "camelCase",
          confidence: 0.94,
          stability: "high",
          extensions: {
            eslint: {
              rule: "@typescript-eslint/naming-convention",
              options: [{ selector: "variable", format: ["camelCase"] }],
            },
          },
        },
      },
    });
    const file = generateEslintExport(profile);
    expect(file.content).toContain("@typescript-eslint");
    expect(file.content).toContain("naming-convention");
  });

  it("includes perfectionist import for import ordering rules", () => {
    const profile = makeProfile({
      structure: {
        importOrder: {
          convention: ["builtin", "external", "internal", "relative"],
          confidence: 0.91,
          fixability: "safe",
        },
      },
    });
    const file = generateEslintExport(profile);
    expect(file.content).toContain("perfectionist");
  });

  it("maps confidence to correct severity levels", () => {
    const profile = makeProfile({
      naming: {
        highConf: {
          convention: "camelCase",
          confidence: 0.90,
          extensions: {
            eslint: { rule: "some-plugin/high-rule" },
          },
        },
        medConf: {
          convention: "camelCase",
          confidence: 0.70,
          extensions: {
            eslint: { rule: "some-plugin/med-rule" },
          },
        },
      },
    });
    const file = generateEslintExport(profile);
    expect(file.content).toContain('"error"');
    expect(file.content).toContain('"warn"');
  });

  it("excludes rules below info threshold", () => {
    const profile = makeProfile({
      naming: {
        lowConf: {
          convention: "camelCase",
          confidence: 0.20,
          extensions: {
            eslint: { rule: "some-plugin/low-rule" },
          },
        },
      },
    });
    const file = generateEslintExport(profile);
    expect(file.content).not.toContain("low-rule");
  });
});
