import type { Profile } from "../schema/profile.js";
import type { GeneratedFile } from "./types.js";
import {
  extractAllRules,
  type RuleEntry,
} from "./template-helpers.js";

function capitalize(str: string): string {
  const spaced = str.replace(/([A-Z])/g, " $1");
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

function formatConvention(convention: unknown): string {
  if (typeof convention === "string") return convention;
  if (typeof convention === "number") return String(convention);
  if (typeof convention === "boolean") return String(convention);
  return JSON.stringify(convention);
}

function groupByCategory(rules: RuleEntry[]): Map<string, RuleEntry[]> {
  const byCategory = new Map<string, RuleEntry[]>();
  for (const rule of rules) {
    const existing = byCategory.get(rule.category) ?? [];
    existing.push(rule);
    byCategory.set(rule.category, existing);
  }
  return byCategory;
}

export function generateMarkdownExport(profile: Profile): GeneratedFile {
  const allRules = extractAllRules(profile);
  const byCategory = groupByCategory(allRules);
  const lines: string[] = [];

  lines.push(`# ${profile.author}'s Code Style Guide`);
  lines.push("");
  lines.push(`> Generated by codewatch on ${profile.generated}`);
  lines.push(
    `> Sources: ${profile.sources.length > 0 ? profile.sources.join(", ") : "N/A"}`,
  );
  lines.push("");

  for (const [category, rules] of byCategory) {
    lines.push(`## ${capitalize(category)}`);
    lines.push("");

    const sorted = [...rules].sort((a, b) => b.confidence - a.confidence);
    for (const rule of sorted) {
      const confPct = (rule.confidence * 100).toFixed(0);
      const value = formatConvention(rule.convention);

      lines.push(`### ${capitalize(rule.name)}`);
      lines.push("");
      lines.push(
        `**Convention**: \`${value}\` | **Confidence**: ${confPct}%${rule.stability ? ` | **Stability**: ${rule.stability}` : ""}`,
      );
      lines.push("");

      if (rule.description) {
        lines.push(rule.description);
        lines.push("");
      }

      if (rule.examples && rule.examples.length > 0) {
        for (const example of rule.examples) {
          if (example.good) {
            lines.push("```typescript");
            lines.push("// Preferred");
            lines.push(example.good);
            lines.push("```");
            lines.push("");
          }
          if (example.bad) {
            lines.push("```typescript");
            lines.push("// Avoid");
            lines.push(example.bad);
            lines.push("```");
            lines.push("");
          }
        }
      }
    }
  }

  return {
    path: "style-guide.md",
    content: lines.join("\n"),
  };
}
