import { describe, it, expect } from "vitest";
import { generateRuffExport } from "./ruff.js";
import type { Profile } from "../schema/profile.js";

function makeProfile(overrides: Partial<Profile> = {}): Profile {
  return {
    schemaVersion: "1.0.0",
    author: "testuser",
    generated: "2026-02-27",
    sources: [],
    naming: {},
    structure: {},
    documentation: {},
    errorHandling: {},
    formatting: {},
    patterns: {},
    idioms: { detected: [] },
    antiPatterns: { acknowledged: [] },
    overrides: [],
    severityThresholds: { error: 0.85, warn: 0.60, info: 0.40 },
    ...overrides,
  };
}

describe("generateRuffExport", () => {
  it("returns a file with ruff.toml path", () => {
    const file = generateRuffExport(makeProfile());
    expect(file.path).toBe("ruff.toml");
  });

  it("generates valid TOML with lint section", () => {
    const profile = makeProfile({
      naming: {
        variables: { convention: "snake_case", confidence: 0.92, stability: "high" },
      },
    });
    const file = generateRuffExport(profile);
    expect(file.content).toContain("[lint]");
    expect(file.content).toContain("select");
  });

  it("includes a header comment", () => {
    const file = generateRuffExport(makeProfile());
    expect(file.content).toContain("# Generated by codewatch");
  });

  it("includes naming rules when naming section has entries", () => {
    const profile = makeProfile({
      naming: {
        variables: {
          convention: "snake_case",
          confidence: 0.92,
          stability: "high",
          extensions: { ruff: { codes: ["N806"] } },
        },
      },
    });
    const file = generateRuffExport(profile);
    expect(file.content).toContain('"N"');
  });

  it("includes import ordering rules", () => {
    const profile = makeProfile({
      structure: {
        importOrder: {
          convention: ["builtin", "external", "internal", "relative"],
          confidence: 0.91,
        },
      },
    });
    const file = generateRuffExport(profile);
    expect(file.content).toContain('"I"');
  });

  it("includes docstring convention", () => {
    const profile = makeProfile({
      documentation: {
        functionDocs: { convention: "google", confidence: 0.85 },
      },
    });
    const file = generateRuffExport(profile);
    expect(file.content).toContain("google");
    expect(file.content).toContain("[lint.pydocstyle]");
  });

  it("includes mccabe complexity for functionMaxLines", () => {
    const profile = makeProfile({
      structure: {
        functionMaxLines: { convention: 30, confidence: 0.78 },
      },
    });
    const file = generateRuffExport(profile);
    expect(file.content).toContain("[lint.mccabe]");
    expect(file.content).toContain("max-complexity = 30");
  });

  it("includes line-length from formatting", () => {
    const profile = makeProfile({
      formatting: {
        lineLength: { convention: 120, confidence: 0.95, stability: "high" },
      },
    });
    const file = generateRuffExport(profile);
    expect(file.content).toContain("line-length = 120");
  });
});
