import type { Profile } from "../schema/profile.js";
import type { StyleRule } from "../schema/style-rule.js";
import type { GeneratedFile } from "./types.js";

interface RuffConfig {
  lineLength?: number;
  lint: {
    select: string[];
    ignore: string[];
    fixable: string[];
    mccabe?: { maxComplexity: number };
    pydocstyle?: { convention: string };
    isort?: { sectionOrder: string[] };
  };
}

const CATEGORY_KEYS = [
  "naming",
  "structure",
  "documentation",
  "errorHandling",
  "formatting",
  "patterns",
] as const;

function buildRuffConfig(profile: Profile): RuffConfig {
  const thresholds = profile.severityThresholds;
  const select = new Set<string>();
  const fixable = new Set<string>(["ALL"]);
  let mccabe: { maxComplexity: number } | undefined;
  let pydocstyle: { convention: string } | undefined;
  let isort: { sectionOrder: string[] } | undefined;

  for (const category of CATEGORY_KEYS) {
    const section = profile[category];
    if (!section) continue;

    for (const [name, rule] of Object.entries(
      section as Record<string, StyleRule>,
    )) {
      if (rule.confidence < thresholds.info) continue;

      if (rule.extensions?.ruff) {
        const ext = rule.extensions.ruff as { codes?: string[] };
        if (ext.codes) {
          for (const code of ext.codes) {
            select.add(code.replace(/\d+$/, ""));
          }
        }
      }

      if (category === "naming") {
        select.add("N");
      }

      if (category === "structure" && name === "importOrder") {
        select.add("I");
        if (Array.isArray(rule.convention)) {
          isort = { sectionOrder: rule.convention as string[] };
        }
      }

      if (category === "documentation" && name === "functionDocs") {
        select.add("D");
        if (typeof rule.convention === "string") {
          pydocstyle = { convention: rule.convention };
        }
      }

      if (category === "structure" && name === "functionMaxLines") {
        select.add("C90");
        if (typeof rule.convention === "number") {
          mccabe = { maxComplexity: rule.convention };
        }
      }
    }
  }

  let lineLength: number | undefined;
  const lineLengthRule = profile.formatting?.lineLength;
  if (lineLengthRule && typeof lineLengthRule.convention === "number") {
    lineLength = lineLengthRule.convention;
  }

  return {
    lineLength,
    lint: {
      select: [...select].sort(),
      ignore: [],
      fixable: [...fixable],
      mccabe,
      pydocstyle,
      isort,
    },
  };
}

function toTomlArray(items: string[]): string {
  return `[${items.map((s) => `"${s}"`).join(", ")}]`;
}

function serializeToToml(config: RuffConfig): string {
  const lines: string[] = [];

  if (config.lineLength !== undefined) {
    lines.push(`line-length = ${config.lineLength}`);
    lines.push("");
  }

  lines.push("[lint]");
  if (config.lint.select.length > 0) {
    lines.push(`select = ${toTomlArray(config.lint.select)}`);
  }
  if (config.lint.ignore.length > 0) {
    lines.push(`ignore = ${toTomlArray(config.lint.ignore)}`);
  }
  if (config.lint.fixable.length > 0) {
    lines.push(`fixable = ${toTomlArray(config.lint.fixable)}`);
  }
  lines.push("");

  if (config.lint.mccabe) {
    lines.push("[lint.mccabe]");
    lines.push(`max-complexity = ${config.lint.mccabe.maxComplexity}`);
    lines.push("");
  }

  if (config.lint.pydocstyle) {
    lines.push("[lint.pydocstyle]");
    lines.push(`convention = "${config.lint.pydocstyle.convention}"`);
    lines.push("");
  }

  if (config.lint.isort) {
    lines.push("[lint.isort]");
    lines.push(
      `section-order = ${toTomlArray(config.lint.isort.sectionOrder)}`,
    );
    lines.push("");
  }

  return lines.join("\n");
}

export function generateRuffExport(profile: Profile): GeneratedFile {
  const config = buildRuffConfig(profile);

  const header = [
    `# Generated by codewatch for ${profile.author}`,
    `# Date: ${profile.generated}`,
    `# Do not edit manually - regenerate with: codewatch export --format ruff`,
    "",
  ].join("\n");

  return {
    path: "ruff.toml",
    content: header + serializeToToml(config),
  };
}
