#!/usr/bin/env node
// Print the `area` section of the task category registry, derived from the `$tiers` map in
// .codewatch/check.json plus scripts/areas-external.json. `--write <categories.yml>` swaps that
// section into an existing registry and leaves every other byte of the file alone.
import { readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { parse } from "yaml";
import { TIERS, findTiersRule } from "./new-package.mjs";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const AREA_ID = /^[a-z0-9][a-z0-9-]*$/;
const AREA_KEY = /^area\s*:/;
// A line at column 0 that is not a comment or a sequence item starts the next top-level key.
const TOP_LEVEL = /^[^\s#-]/;

const tierValue = (tier) => (/^\d+$/.test(tier) ? Number(tier) : tier);

function readTiers(root) {
  const rule = findTiersRule(JSON.parse(readFileSync(join(root, ".codewatch", "check.json"), "utf8")));
  if (!rule) throw new Error(".codewatch/check.json needs a layered-deps rule with $tiers");
  return rule.$tiers;
}

const readExternal = (root) => JSON.parse(readFileSync(join(root, "scripts", "areas-external.json"), "utf8")).areas;

/** One area per `$tiers` path (id = directory basename) in tier order, then the external products. */
export function deriveAreas(tiers, external) {
  const internal = TIERS.flatMap((tier) =>
    (tiers[tier] ?? []).map((path) => ({ id: basename(path), tier: tierValue(tier), path })),
  );
  return [...internal, ...external];
}

export const loadAreas = (root = ROOT) => deriveAreas(readTiers(root), readExternal(root));

/** Structure rule: every `$tiers` path yields a valid area id, and no two areas share an id. */
export function checkAreas(root) {
  const areas = loadAreas(root);
  const invalid = areas
    .filter((area) => !AREA_ID.test(area.id))
    .map((area) => `\`${area.path ?? area.id}\` has no area: \`${area.id}\` is not a lowercase slug. Rename the directory.`);
  const ids = areas.map((area) => area.id);
  const repeated = [...new Set(ids.filter((id, index) => ids.indexOf(id) !== index))];
  const duplicates = repeated.map(
    (id) => `Area id \`${id}\` is used twice. Rename one directory, or drop it from \`scripts/areas-external.json\`.`,
  );
  return [...invalid, ...duplicates];
}

const formatArea = ({ id, tier, path }) => `  - { id: ${id}, tier: ${tier}${path ? `, path: ${path}` : ""} }`;

export function renderAreaSection(areas) {
  const header = "  # Generated by titan-platform scripts/areas.mjs; edit $tiers or areas-external.json instead.";
  return ["area:", header, ...areas.map(formatArea)].join("\n");
}

/**
 * Replaces the top-level `area:` block, or appends one when the file has none. Blank lines and
 * column-0 comments just before the next key stay put, since they introduce that key.
 */
export function replaceAreaSection(text, section) {
  const lines = text.split("\n");
  const start = lines.findIndex((line) => AREA_KEY.test(line));
  if (start === -1) return `${text}${text === "" || text.endsWith("\n") ? "" : "\n"}${section}\n`;
  let end = lines.findIndex((line, i) => i > start && TOP_LEVEL.test(line));
  if (end === -1) end = lines.length;
  while (end > start + 1 && /^(#.*)?\s*$/.test(lines[end - 1])) end -= 1;
  return [...lines.slice(0, start), ...section.split("\n"), ...lines.slice(end)].join("\n");
}

async function validateRegistry(text, file) {
  const { CategoryRegistrySchema } = await import(pathToFileURL(join(ROOT, "packages", "pm", "dist", "index.js")).href);
  const result = CategoryRegistrySchema.safeParse(parse(text));
  if (!result.success) throw new Error(`${file} would not be a valid category registry: ${result.error.message}`);
}

export async function writeAreas(file, areas) {
  const next = replaceAreaSection(readFileSync(file, "utf8"), renderAreaSection(areas));
  await validateRegistry(next, file);
  writeFileSync(file, next);
}

async function main(argv) {
  const areas = loadAreas();
  if (argv[0] !== "--write") return console.log(renderAreaSection(areas));
  if (!argv[1]) throw new Error("usage: node scripts/areas.mjs [--write <categories.yml>]");
  await writeAreas(argv[1], areas);
  console.log(`wrote ${areas.length} areas to ${argv[1]}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main(process.argv.slice(2));
