export * from "./shell/index.js";
export { parseHookEvent } from "./event.js";
export type { HookEvent, MalformedEvent, ReadEvent, WriteEvent } from "./event.js";
export { GUARDED_PATHS } from "./paths.js";
export type { GuardedList, GuardedPath } from "./paths.js";
export { SPELLINGS } from "./spellings.js";
export type { FamilyName, SpellingId } from "./spellings.js";
export { classify } from "./classify.js";
export type { ClassifiedAction, ClassifyContext, Family, GuardedAction } from "./types.js";
export { checkPreferences, PREFERENCES } from "./families/preference.js";
export type { PreferenceContext, PreferenceHit, PreferenceId } from "./families/preference.js";
export { AGENT_CANDIDATES, BYPASS_VAR, observeActor } from "./actor.js";
export type { ActorObservation } from "./actor.js";
export { decide } from "./decide.js";
export type { GuardDecision, Matched } from "./decide.js";
export { formatDecisionLine, formatErrorLine, logPath } from "./log.js";
export type { DecisionLine, ErrorClass, ErrorLine } from "./log.js";
export { handle } from "./hook.js";
export type { DecideFn, HookPort, HookResult } from "./hook.js";
export { nodeContext } from "./context.js";
export type { ReadFs } from "./context.js";
export { SETTINGS_ENTRY } from "./cli.js";
