const lines = (...ls: string[]): string => `${ls.join("\n")}\n`;

/**
 * A small Python project with one planted case per code kind and test kind
 * (TP-2170). `app/cli.py` is the CLI whose only test checks substrings.
 */
export const TEST_KINDS_PROJECT: Record<string, string> = {
  "pyproject.toml": lines("[project]", 'name = "app"', "", "[project.scripts]", 'greet = "app.cli:run"', "", "[tool.other]", 'x = "app.core:shout"'),
  "app/__init__.py": "",
  "app/core.py": lines(
    "import json",
    "import os",
    "import subprocess",
    "import sys",
    "import numpy",
    "import boto3",
    "from app import io_helpers",
    "from pathlib import Path",
    "",
    "CACHE = {}",
    "",
    "def shout(name):",
    "    return name.upper() + '!'",
    "",
    "def join_parts(a, b):",
    "    return os.path.join(a, b)",
    "",
    "def parse_config(text):",
    "    return text.split('=')",
    "",
    "def load(text):",
    "    return json.loads(text)",
    "",
    "def dump(data):",
    "    return json.dumps(data)",
    "",
    "def save(path, text):",
    "    Path(path).write_text(text)",
    "",
    "def run_git():",
    "    return subprocess.run(['git', 'status'])",
    "",
    "def remember(key, value):",
    "    CACHE[key] = value",
    "",
    "def shout_and_save(path, name):",
    "    save(path, shout(name))",
    "",
    "def slugify(title):",
    "    return str(title).replace(' ', '-').strip()",
    "",
    "def collect():",
    "    CACHE = []",
    "    CACHE.append(1)",
    "    return CACHE",
    "",
    "def touch_marker(marker: Path):",
    "    marker.touch()",
    "",
    "def read_cfg(path):",
    "    return path.read_text()",
    "",
    "def make_dirs(out_dir):",
    "    out_dir.mkdir(parents=True)",
    "",
    "def write_cfg(cfg_path: Path, text):",
    "    with cfg_path.open('w') as f:",
    "        f.write(text)",
    "",
    "def move(src: Path, dst):",
    "    src.rename(dst)",
    "",
    "def rename_columns(frame):",
    "    return frame.rename(columns={'a': 'b'})",
    "",
    "def report(x):",
    "    io_helpers.write_out(x)",
    "",
    "def ask():",
    "    return input('name? ')",
    "",
    "def read_stdin():",
    "    return sys.stdin.read()",
    "",
    "def warn(message):",
    "    sys.stderr.write(message)",
    "",
    "def mean(xs):",
    "    return numpy.mean(xs)",
    "",
    "def squares(xs):",
    "    out = []",
    "    for x in xs:",
    "        out.append(x * x)",
    "    return sorted(out)",
    "",
    "s3 = boto3.client('s3')",
    "",
    "def mv(src, dst):",
    "    src.replace(dst)",
    "",
    "def copy_object(key):",
    "    return s3.copy(key, 'backup')",
    "",
    "def list_keys():",
    "    return s3.keys()",
    "",
    "def clone(client, key):",
    "    return client.copy(key)",
    "",
    "def wait_for(t):",
    "    t.join()",
    "",
    "def peek(f):",
    "    return next(f)",
    "",
    "def set_mode():",
    "    os.environ['MODE'] = 'x'",
    "",
    "def tally(words):",
    "    counts = {}",
    "    for w in words:",
    "        counts[w] = counts.get(w, 0) + 1",
    "    return counts",
    "",
    "def csv_line(cells):",
    "    return ', '.join(cells)",
    "",
    "def shout_twice(name):",
    "    return shout(name) + shout(name)",
    "",
    "class Counter:",
    "    def bump(self):",
    "        self.n += 1",
    "",
    "    def grow(self, x):",
    "        self.items.append(x)",
    "",
    "class Store:",
    "    def save(self, text):",
    "        self.path.write_text(text)",
    "",
    "    def load(self):",
    "        with self.root.open() as f:",
    "            return f.read()",
    "",
    "class Config:",
    "    def parse(self, text):",
    "        return text",
  ),
  "app/cli.py": lines(
    "import argparse",
    "from app.core import shout",
    "",
    "def main(argv=None):",
    "    parser = argparse.ArgumentParser()",
    "    parser.add_argument('name')",
    "    args = parser.parse_args(argv)",
    "    print(shout(args.name))",
    "    return 0",
    "",
    "def run():",
    "    return main()",
    "",
    "def guarded():",
    "    return 1",
    "",
    "if __name__ == '__main__':",
    "    guarded()",
  ),
  "app/web.py": lines(
    "from flask import Flask",
    "app = Flask(__name__)",
    "",
    "@app.route('/hello')",
    "def hello():",
    "    return 'hi'",
  ),
  "app/io_helpers.py": lines("def write_out(x):", "    with open('out.txt', 'w') as f:", "        f.write(x)"),
  "app/other.py": lines("def other_main():", "    print('other')"),
  "tests/test_other.py": lines(
    "def test_other_output(cli_output):",
    "    assert cli_output == 'other'",
    "    assert 'oth' in cli_output",
  ),
  "app/clicmd.py": lines(
    "import click",
    "",
    "@click.command()",
    "@click.argument('name')",
    "def greet(name):",
    "    return name",
    "",
    "@click.group()",
    "def cli():",
    "    pass",
    "",
    "@cli.command()",
    "def sub():",
    "    return 'sub'",
    "",
    "@cli.command()",
    "def other():",
    "    return 'other'",
  ),
  "tests/test_cli.py": lines(
    "from app.cli import main",
    "",
    "def test_main_greets(capsys):",
    "    main(['ann'])",
    "    out = capsys.readouterr().out",
    "    assert 'ANN' in out",
    "    assert out.startswith('ANN')",
  ),
  "tests/test_clicmd.py": lines(
    "from unittest.mock import Mock",
    "from click.testing import CliRunner",
    "from app.clicmd import greet, cli, sub, other",
    "",
    "def test_greet_snapshot(snapshot):",
    "    result = CliRunner().invoke(greet, ['Ann'])",
    "    assert result.output == snapshot",
    "",
    "def test_greet_needs_a_name():",
    "    result = CliRunner().invoke(greet, [])",
    "    assert result.exit_code != 0",
    "",
    "def test_greet_with_a_typed_runner(runner: CliRunner):",
    "    result = runner.invoke(greet, ['--bad'])",
    "    assert result.exit_code == 2",
    "",
    "def test_mock_invoke_is_no_cli_run():",
    "    Mock().invoke(sub)",
    "",
    "def test_alias_credits_nothing():",
    "    other = sub",
    "    result = CliRunner().invoke(other)",
    "    assert result.exit_code == 0",
    "",
    "def test_group_runs_a_subcommand():",
    "    runner = CliRunner()",
    "    result = runner.invoke(cli, ['sub'])",
    "    assert result.output == 'sub\\n'",
  ),
  "tests/test_core.py": lines(
    "import pytest",
    "from pathlib import Path",
    "from hypothesis import given, strategies as st",
    "from app.core import shout, parse_config, dump, load, save",
    "",
    "def test_shout_exact():",
    "    assert shout('a') == 'A!'",
    "",
    "def test_parse_rejects_garbage():",
    "    with pytest.raises(ValueError):",
    "        parse_config('{')",
    "",
    "@given(st.text())",
    "def test_shout_property(s):",
    "    assert shout(s).endswith('!')",
    "",
    "def test_roundtrip():",
    "    data = {'a': 1}",
    "    assert load(dump(data)) == data",
    "",
    "def test_save_golden(tmp_path):",
    "    save(tmp_path / 'out.txt', 'x')",
    "    assert (tmp_path / 'out.txt').read_text() == Path('tests/golden/out.txt').read_text()",
  ),
};
