const lines = (...ls: string[]): string => `${ls.join("\n")}\n`;

/**
 * A small Python project with one planted case per code kind and test kind
 * (TP-2170). `app/cli.py` is the CLI whose only test checks substrings.
 */
export const TEST_KINDS_PROJECT: Record<string, string> = {
  "pyproject.toml": lines("[project]", 'name = "app"', "", "[project.scripts]", 'greet = "app.cli:run"', "", "[tool.other]", 'x = "app.core:shout"'),
  "app/__init__.py": "",
  "app/core.py": lines(
    "import json",
    "import os",
    "import subprocess",
    "from pathlib import Path",
    "",
    "CACHE = {}",
    "",
    "def shout(name):",
    "    return name.upper() + '!'",
    "",
    "def join_parts(a, b):",
    "    return os.path.join(a, b)",
    "",
    "def parse_config(text):",
    "    return text.split('=')",
    "",
    "def load(text):",
    "    return json.loads(text)",
    "",
    "def dump(data):",
    "    return json.dumps(data)",
    "",
    "def save(path, text):",
    "    Path(path).write_text(text)",
    "",
    "def run_git():",
    "    return subprocess.run(['git', 'status'])",
    "",
    "def remember(key, value):",
    "    CACHE[key] = value",
    "",
    "def shout_and_save(path, name):",
    "    save(path, shout(name))",
    "",
    "def slugify(title):",
    "    return title.replace(' ', '-').strip()",
    "",
    "def collect():",
    "    CACHE = []",
    "    CACHE.append(1)",
    "    return CACHE",
    "",
    "def touch_marker(marker: Path):",
    "    marker.touch()",
    "",
    "class Config:",
    "    def parse(self, text):",
    "        return text",
  ),
  "app/cli.py": lines(
    "import argparse",
    "from app.core import shout",
    "",
    "def main(argv=None):",
    "    parser = argparse.ArgumentParser()",
    "    parser.add_argument('name')",
    "    args = parser.parse_args(argv)",
    "    print(shout(args.name))",
    "    return 0",
    "",
    "def run():",
    "    return main()",
    "",
    "def guarded():",
    "    return 1",
    "",
    "if __name__ == '__main__':",
    "    guarded()",
  ),
  "app/web.py": lines(
    "from flask import Flask",
    "app = Flask(__name__)",
    "",
    "@app.route('/hello')",
    "def hello():",
    "    return 'hi'",
  ),
  "app/clicmd.py": lines(
    "import click",
    "",
    "@click.command()",
    "@click.argument('name')",
    "def greet(name):",
    "    return name",
  ),
  "tests/test_cli.py": lines(
    "from app.cli import main",
    "",
    "def test_main_greets(capsys):",
    "    main(['ann'])",
    "    out = capsys.readouterr().out",
    "    assert 'ANN' in out",
    "    assert out.startswith('ANN')",
  ),
  "tests/test_clicmd.py": lines(
    "from click.testing import CliRunner",
    "from app.clicmd import greet",
    "",
    "def test_greet_snapshot(snapshot):",
    "    result = CliRunner().invoke(greet, ['Ann'])",
    "    assert result.output == snapshot",
    "",
    "def test_greet_needs_a_name():",
    "    result = CliRunner().invoke(greet, [])",
    "    assert result.exit_code != 0",
  ),
  "tests/test_core.py": lines(
    "import pytest",
    "from pathlib import Path",
    "from hypothesis import given, strategies as st",
    "from app.core import shout, parse_config, dump, load, save",
    "",
    "def test_shout_exact():",
    "    assert shout('a') == 'A!'",
    "",
    "def test_parse_rejects_garbage():",
    "    with pytest.raises(ValueError):",
    "        parse_config('{')",
    "",
    "@given(st.text())",
    "def test_shout_property(s):",
    "    assert shout(s).endswith('!')",
    "",
    "def test_roundtrip():",
    "    data = {'a': 1}",
    "    assert load(dump(data)) == data",
    "",
    "def test_save_golden(tmp_path):",
    "    save(tmp_path / 'out.txt', 'x')",
    "    assert (tmp_path / 'out.txt').read_text() == Path('tests/golden/out.txt').read_text()",
  ),
};
