import { describe, expect, it } from "vitest";
import { classifyInbound, contentHash, type WakeCause } from "./wake-cause.js";
import type { Json } from "./text.js";

/** Record shapes are trimmed copies of real transcript lines; all text is a placeholder. */
function userRecord(fields: Json): Json {
  return {
    parentUuid: "00000000-0000-4000-8000-000000000001",
    isSidechain: false,
    promptId: "00000000-0000-4000-8000-000000000002",
    type: "user",
    uuid: "00000000-0000-4000-8000-000000000003",
    timestamp: "2026-09-20T00:00:00.000Z",
    userType: "external",
    entrypoint: "cli",
    cwd: "/redacted/project",
    sessionId: "00000000-0000-4000-8000-000000000004",
    version: "2.1.278",
    gitBranch: "HEAD",
    ...fields,
  };
}

function textRecord(text: string, fields: Json = {}): Json {
  return userRecord({ message: { role: "user", content: text }, ...fields });
}

const CHANNEL_TAG = '<channel source="plugin:agent-chat:agent-chat" from="peer-name" msg_id="0f2cc8a1" thread_depth="1">';

const CASES: ReadonlyArray<readonly [WakeCause, Json]> = [
  ["compaction", textRecord("This session is being continued from a previous conversation that ran out of context. [summary redacted]", { isCompactSummary: true })],
  ["ask_user_answer", userRecord({
    message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_0000000000000000000001", content: "The user answered: [redacted]" }] },
    toolUseResult: {
      questions: [{ question: "[question redacted]", header: "Scope", options: [{ label: "[label]", description: "[description]" }], multiSelect: false }],
      answers: { "[question redacted]": "[answer redacted]" },
      annotations: {},
    },
  })],
  ["tool_result", userRecord({
    message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_0000000000000000000002", content: "[command output redacted]" }] },
    toolUseResult: { stdout: "[redacted]", stderr: "", interrupted: false },
  })],
  ["channel_message", textRecord(`${CHANNEL_TAG}\n[message body redacted]\n</channel>`, { isMeta: true })],
  ["channel_system", textRecord('<channel source="plugin:agent-chat:agent-chat" from="agent-chat" system="true" count="1">\nLifecycle: peer-name agent_exited\n</channel>', { isMeta: true })],
  ["task_notification", textRecord("<task-notification>\n<task-id>bnoxejknh</task-id>\n<tool-use-id>toolu_0000000000000000000003</tool-use-id>\n<status>completed</status>\n</task-notification>")],
  ["scheduled_wakeup", textRecord("[2 prior /loop wakeups found nothing actionable; loop is healthy.]", { isMeta: true })],
  ["usage_limit_resume", textRecord("Your claude.ai usage limit has reset. Continue the task you were working on when the limit was reached; do not repeat work that is already complete.", { isMeta: true, origin: { kind: "auto-continuation" }, promptSource: "system" })],
  ["harness_resume", userRecord({ message: { role: "user", content: [{ type: "text", text: "Continue from where you left off." }] }, isMeta: true })],
  ["local_command", textRecord("<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>\n<command-name>active-work</command-name>", { isMeta: true })],
  ["image_meta", textRecord("[Image: original 3840x1096, displayed at 2000x571. Multiply coordinates by 1.92 to map to original image.]", { isMeta: true })],
  ["hook_or_reminder", textRecord("<system-reminder>\n[reminder body redacted]\n</system-reminder>", { isMeta: true })],
  ["human_typed", textRecord("[typed prompt redacted]")],
];

describe("classifyInbound", () => {
  it.each(CASES)("classifies %s", (cause, record) => {
    expect(classifyInbound(record).cause).toBe(cause);
  });

  it("covers every WakeCause value once", () => {
    const seen = CASES.map(([cause]) => cause);
    expect(new Set(seen).size).toBe(seen.length);
  });

  it("a task-notification block is not human_typed", () => {
    const [, record] = CASES.find(([cause]) => cause === "task_notification")!;
    const inbound = classifyInbound(record);
    expect(inbound.cause).toBe("task_notification");
    expect(inbound.detail).toBe("bnoxejknh");
    expect(inbound.delivery).toBe("turn_start");
  });

  it("an AskUserQuestion result is ask_user_answer when toolUseResult carries answers", () => {
    const [, record] = CASES.find(([cause]) => cause === "ask_user_answer")!;
    const inbound = classifyInbound(record);
    expect(inbound.cause).toBe("ask_user_answer");
    expect(inbound.delivery).toBe("tool_result");
    expect(inbound.toolUseId).toBe("toolu_0000000000000000000001");
  });

  it("a tool result without questions stays tool_result", () => {
    const [, record] = CASES.find(([cause]) => cause === "tool_result")!;
    expect(classifyInbound(record)).toMatchObject({ cause: "tool_result", delivery: "tool_result", isError: false });
  });

  it("reports an errored tool result", () => {
    const record = userRecord({
      message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_0000000000000000000004", content: "[error redacted]", is_error: true }] },
      toolUseResult: "[error redacted]",
    });
    expect(classifyInbound(record)).toMatchObject({ cause: "tool_result", isError: true });
  });

  it("parses the channel attributes of an inbound peer message", () => {
    const [, record] = CASES.find(([cause]) => cause === "channel_message")!;
    expect(classifyInbound(record)).toMatchObject({
      originServer: "plugin:agent-chat:agent-chat",
      fromName: "peer-name",
      msgId: "0f2cc8a1",
      delivery: "turn_start",
    });
  });

  it("a queued_command attachment with a channel origin is a mid_loop channel_message", () => {
    const record: Json = {
      parentUuid: "00000000-0000-4000-8000-000000000005",
      isSidechain: false,
      type: "attachment",
      uuid: "00000000-0000-4000-8000-000000000006",
      timestamp: "2026-09-20T00:00:00.000Z",
      attachment: {
        type: "queued_command",
        prompt: `${CHANNEL_TAG}\n[message body redacted]\n</channel>`,
        source_uuid: "00000000-0000-4000-8000-000000000007",
        commandMode: "prompt",
        origin: { kind: "channel", server: "plugin:agent-chat:agent-chat" },
        timestamp: "2026-09-20T00:00:00.000Z",
        isMeta: true,
      },
    };
    expect(classifyInbound(record)).toMatchObject({
      cause: "channel_message",
      delivery: "mid_loop",
      originServer: "plugin:agent-chat:agent-chat",
      fromName: "peer-name",
      toolUseId: null,
    });
  });

  it("names the marker that made a record a hook_or_reminder", () => {
    const [, record] = CASES.find(([cause]) => cause === "hook_or_reminder")!;
    expect(classifyInbound(record).detail).toBe("system_reminder");
  });
});

describe("contentHash", () => {
  it("is stable for the first 512 characters", () => {
    const head = "x".repeat(512);
    expect(contentHash(`${head}tail one`)).toBe(contentHash(`${head}tail two`));
    expect(contentHash(`${head}tail`)).not.toBe(contentHash(`y${head}`));
  });

  it("counts every character of the record, not just the hashed head", () => {
    const record = textRecord("z".repeat(600));
    expect(classifyInbound(record).chars).toBe(600);
    expect(classifyInbound(record).contentHash).toBe(contentHash("z".repeat(512)));
  });
});
